import { listOptions } from "./lists.js"
import { Character } from "./character.js"
import { inputsArray, newInputsArray } from "./inputs.js"
import { appController } from "./controller/controller.js"

const startCharacter = createCharacter(listOptions)
const currentlyCharacter = appController.turnIntoProperty(inputsArray)
const userInputs = {}

function createCharacter(object){
    return new Character(object)
}

function startApp(){
    appController.addClickEventToAddPropertyButton(appController.pegarInputsManuais, userInputs, inputsArray)
    appController.getInputsAutoGenerated(inputsArray, userInputs, currentlyCharacter, startCharacter)
    appController.pegarInputsManuais(inputsArray, userInputs)
    appController.pegarNovosInputsAutomaticos(newInputsArray, startCharacter, currentlyCharacter, userInputs)
    appController.addClickEventToSaveFileButton(userInputs)
}
startApp()