export const nameList = [
    "Agnès",
    "Aliénor",
    "Blanche",
    "Catherine",
    "Dhuoda",
    "Éléonore",
    "Isabelle",
    "Jeanne",
    "Marguerite",
    "Philippa",
    "Rosalie",
    "Yolande",
    "Zéphyrine",
    "Adélaïde",
    "Amélie",
    "Claire",
    "Delphine",
    "Élise",
    "Félicité",
    "Geneviève",
    "Hélène"
]

export const cityList = [
    "Carcassonne",
    "Les Baux-de-Provence",
    "Provins",
    "Aigues-Mortes",
    "Avignon",
    "Conques",
    "Rocamadour",
    "Laon",
    "Montrésor",
    "Collonges-la-Rouge",
    "Gordes",
    "Narbonne",
    "Amiens",
    "Arles",
    "Bordeaux",
    "Colmar",
    "Grenoble",
    "Lille",
    "Lyon",
    "Marselha"
];

export const nationalitList = [
    "Comté de Champagne",
    "Fief de Bourgogne",
    "Fief de Normandie",
    "Fief de Flandre",
    "Fief de Aquitaine",
    "Fief de Lorraine",
    "Fief d'Hainaut",
    "Fief d'Artois",
    "Fief d'Alsace",
    "Fief de Touraine",
    "Fief de Poitou",
    "Fief d'Anjou",
    "Fief d'Auvergne",
    "Fief de Gascogne",
    "Fief de Guienne",
    "Fief de Limousin",
    "Fief de la Marche d'Espagne",
    "Fief de Brabant",
    "Fief de Westphalie"
];
