
// PEGAR OS INPUTS DO USUARIO (MANUALMENTE)
export function addInputEvent(id, property, listUserInputs){    
    document.getElementById(id).addEventListener('input', (e)=>{ 
        listUserInputs[property] = `# ${property} \n ${e.target.value} \n\n`
    })
}    

export function pegarInputsManuais(inputsArray, listUserInputs){
    inputsArray.map(item=>{
        addInputEvent(item.id, item.property, listUserInputs)
    })
}

// PEGAR OS INPUTS GERADOS (AUTOMATICAMENTE)
export function getInputsAutoGenerated(inputsArray, userInputs, currentlyCharacter, startCharacter){
    document.getElementById('generatorButton').addEventListener('click', ()=>{

        const character = startCharacter.default()
        console.log('default: ', character)
        
        function alterarValorInput(id, property){
            if(character[property]){
                document.getElementById(id).value = character[property]
            }
            return
        }
    
        inputsArray.map(item =>{
            alterarValorInput(item.id, item.property)
        })
    
        function salvarValorArquivo(property){
            userInputs[property] = `# ${property} \n ${currentlyCharacter[property].value} \n\n`
        }
        for(let key in currentlyCharacter){
            salvarValorArquivo(key)
        }
    
        return
    })
}

// INPUTS DO SISTEMA
export function turnIntoProperty(list){
    const momentum = {}
    list.map(item=>{
        momentum[item.property] = document.getElementById(item.id)
    })
    return momentum
}

// NOVOS INPUTS
export function newInputValue(id, property, startCharacter, currentlyCharacter, userInputs){
    document.getElementById(id).addEventListener('click', ()=>{
        const character = startCharacter.default()
        
        currentlyCharacter[property].value = character[property]
        userInputs[property] = `# ${property} \n ${character[property]} \n\n`
    })
}

export function pegarNovosInputsAutomaticos(newInputsArray, startCharacter, currentlyCharacter, userInputs){
    newInputsArray.map(item=>{
        return newInputValue(item.id, item.property, startCharacter, currentlyCharacter, userInputs)
    })
}
