import { addClickEventToAddPropertyButton, newProperty } from "../repository/eventHandlers.js"
import { pegarInputsManuais, addInputEvent, turnIntoProperty, getInputsAutoGenerated, pegarNovosInputsAutomaticos } from "../repository/inputHandlers.js"
import { downloadTextAsFile, addClickEventToSaveFileButton } from "../repository/fileOperations.js"


const appController = {
    addClickEventToAddPropertyButton,
    newProperty,
    pegarInputsManuais,
    addInputEvent,
    turnIntoProperty,
    getInputsAutoGenerated,
    downloadTextAsFile,
    addClickEventToSaveFileButton,
    pegarNovosInputsAutomaticos    
}
export {appController}